/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.biblioteca.ui;

import com.mycompany.biblioteca.DAO.relacional.DML;
import com.mycompany.biblioteca.models.Libro;
import com.mycompany.biblioteca.models.Prestamo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JHB
 */
public class TablaPrestamos extends javax.swing.JPanel {

    /**
     * Creates new form TablaPrestamos
     */
    public TablaPrestamos() {
        initComponents();
        iniciarTablaPrestamos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabla = new javax.swing.JTable();

        tbTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTabla;
    // End of variables declaration//GEN-END:variables

    private void iniciarTablaPrestamos() {
        DML listar = new DML();
        DefaultTableModel modelo = new DefaultTableModel();
        ArrayList<Prestamo> listarPrestamos = listar.listaPrestamos();
        
        modelo.addColumn("ID PRESTAMO");
        modelo.addColumn("ID LIBRO");
        modelo.addColumn("ID USUARIO");
        modelo.addColumn("FECHA DE PRESTAMO");
        modelo.addColumn("FECHA LIMITE DE DEVOLUCION");
        modelo.addColumn("MULTA");
        
        for(Prestamo prestamo:listarPrestamos){
            modelo.addRow(new Object[]{
                prestamo.getIdPrestamo(),
                prestamo.getIdLibro(),
                prestamo.getIdUsuario(),
                prestamo.getFechaPrestamo(),
                prestamo.getFechaLimiteDevolucion(),
                prestamo.getMulta()
                
        });
        }
        tbTabla.setModel(modelo);
    }
}
