/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.biblioteca.ui;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author JHB
 */
public class VentanaConfiguracion extends javax.swing.JPanel {

    Color claro = new Color(255,255,255);
    Color oscuro = new Color(45,45,45);
    Color textoNegro = new Color(0,0,0);
    Color textoBlanco = new Color(255,255,255);
    private boolean temaOscuro = false;
    VentanaInsertarPorArchivo insertar = new VentanaInsertarPorArchivo();
    
    
    /**
     * Creates new form VentanaConfiguracion
     */
    public VentanaConfiguracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTema = new javax.swing.JButton();
        btnInsertarArchivo = new javax.swing.JButton();
        panelVentana = new javax.swing.JPanel();

        btnTema.setText("Tema claro/oscuro");
        btnTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemaActionPerformed(evt);
            }
        });

        btnInsertarArchivo.setText("Insertar Paciente por Archivo");
        btnInsertarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVentanaLayout = new javax.swing.GroupLayout(panelVentana);
        panelVentana.setLayout(panelVentanaLayout);
        panelVentanaLayout.setHorizontalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelVentanaLayout.setVerticalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTema, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnInsertarArchivo))
                    .addComponent(panelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarArchivo)
                    .addComponent(btnTema))
                .addGap(18, 18, 18)
                .addComponent(panelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemaActionPerformed
        // TODO add your handling code here:
        if (temaOscuro){
            this.setBackground(claro);
            temaOscuro=false;
        }
        if (!temaOscuro){
            this.setBackground(oscuro);
            temaOscuro=true;
        }
    }//GEN-LAST:event_btnTemaActionPerformed

    private void btnInsertarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarArchivoActionPerformed
        // TODO add your handling code here:
        insertarVentana(insertar);
    }//GEN-LAST:event_btnInsertarArchivoActionPerformed

    public void insertarVentana(JPanel panel){
        panel.setSize(700,320);
        panel.setLocation(0,0);
        panelVentana.removeAll();
        panelVentana.add(panel, BorderLayout.CENTER);
        panelVentana.revalidate();
        panelVentana.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertarArchivo;
    private javax.swing.JButton btnTema;
    private javax.swing.JPanel panelVentana;
    // End of variables declaration//GEN-END:variables
}
