/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.biblioteca.ui;

import com.mycompany.biblioteca.DAO.relacional.DML;
import com.toedter.calendar.JCalendar;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author dam
 */
public class ventanaAñadirPrestamo extends javax.swing.JPanel {

    /**
     * Creates new form ventanaAñadirPrestamo
     */
    DML dml = new DML();
    double multa = 0;
    public ventanaAñadirPrestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblFechaPrestamo = new javax.swing.JLabel();
        lblFechaDevolucion = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        spnLibro = new javax.swing.JSpinner();
        spnUsuario = new javax.swing.JSpinner();
        lblMulta = new javax.swing.JLabel();
        lblMultaRes = new javax.swing.JLabel();
        jcPrestamo = new com.toedter.calendar.JCalendar();
        jcDevolucion = new com.toedter.calendar.JCalendar();

        lblNombre.setText("Id libro");

        lblUsuario.setText("Id usuario");

        lblFechaPrestamo.setText("Fecha de prestamo");

        lblFechaDevolucion.setText("Fecha de devolucion");

        btnAceptar.setText("Añadir");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        spnLibro.setModel(new javax.swing.SpinnerNumberModel());

        spnUsuario.setModel(new javax.swing.SpinnerNumberModel());

        lblMulta.setText("Multa");

        lblMultaRes.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jcPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaPrestamo)
                            .addComponent(lblNombre)
                            .addComponent(spnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaDevolucion)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMulta)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAceptar)
                                .addGap(18, 18, 18)
                                .addComponent(lblMultaRes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(spnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaPrestamo)
                    .addComponent(lblFechaDevolucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblMulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMultaRes)
                            .addComponent(btnAceptar))
                        .addGap(24, 24, 24))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        // TODO add your handling code here:
        
        /*Podemos añadir cosas para que elegir la fecha en la interfaz sea mas comodo
        Pero por ahora queremos que sea mas o menos funcional*/
        int libro = (int)spnLibro.getValue();
        int usuario = (int)spnUsuario.getValue();
        
        JCalendar prestamo = jcPrestamo;
        JCalendar devolucion = jcDevolucion;
        
        java.util.Date fecha1 = prestamo.getDate();
        java.util.Date fecha2 = devolucion.getDate();
        
        LocalDate lDatePres = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate lDateDev = fecha2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Date fechaPrestamo = Date.valueOf(lDatePres);
        Date fechaDevolucion = Date.valueOf(lDateDev);
        
        dml.registrarPrestamo(libro,usuario,fechaPrestamo,fechaDevolucion,multa);
        calcularMulta();
        
        lblMultaRes.setText(String.valueOf(multa));
    }//GEN-LAST:event_btnAceptarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private com.toedter.calendar.JCalendar jcDevolucion;
    private com.toedter.calendar.JCalendar jcPrestamo;
    private javax.swing.JLabel lblFechaDevolucion;
    private javax.swing.JLabel lblFechaPrestamo;
    private javax.swing.JLabel lblMulta;
    private javax.swing.JLabel lblMultaRes;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JSpinner spnLibro;
    private javax.swing.JSpinner spnUsuario;
    // End of variables declaration//GEN-END:variables

    private void calcularMulta(){
        JCalendar prestamo = jcPrestamo;
        JCalendar devolucion = jcDevolucion;
        
        java.util.Date fecha1 =  prestamo.getDate();
        java.util.Date fecha2 = devolucion.getDate();
        
        long diferencia = fecha2.getTime()-fecha1.getTime();
        double diferenciaDias = TimeUnit.MILLISECONDS.toDays(diferencia);
        multa = diferenciaDias*2;
    }
}
