/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.biblioteca.ui;

import com.mycompany.biblioteca.DAO.db4o.ConsultasDB4O;
import com.mycompany.biblioteca.DAO.noRelacional.ConsultasMongoDB;
import com.mycompany.biblioteca.DAO.relacional.DML;
import com.mycompany.biblioteca.models.Usuario;
import com.mycompany.biblioteca.utils.Comprobaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author dam
 */
public class ventanaAñadirUsuario extends javax.swing.JPanel {

    /**
     * Creates new form ventanaAñadirUsuario
     */
    DML dml = new DML();
    ConsultasMongoDB consultasMongoDB = new ConsultasMongoDB();
    ConsultasDB4O consultasDB4O = new ConsultasDB4O();
    Usuario usuario = new Usuario();

    public ventanaAñadirUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNombre = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblTfno = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        cbTipoUsuario = new javax.swing.JComboBox<>();
        tfTelefono = new javax.swing.JTextField();

        lblNombre.setText("Nombre");

        lblEmail.setText("Email");

        lblTipo.setText("Tipo de Usuario");

        lblTfno.setText("Teléfono");

        btnAceptar.setText("Añadir");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        cbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profesor", "Alumno", "Externo" }));
        cbTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipo)
                    .addComponent(lblNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTelefono)
                    .addComponent(lblTfno)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(lblTfno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnAceptar)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        // TODO add your handling code here:

        String nombre = tfNombre.getText();
        String email = tfEmail.getText();
        String tipo = cbTipoUsuario.getSelectedItem().toString();
        int telefono = Integer.parseInt(tfTelefono.getText());

        usuario.setNombre(nombre);
        usuario.setEmail(email);
        usuario.setTipo(tipo);
        usuario.setTelefono(telefono);
        if (Comprobaciones.esEmailValido(email) && Comprobaciones.esNombreValido(nombre) && Comprobaciones.esNumeroTelefonoValido(String.valueOf(telefono))) {

            dml.registrarUsuario(nombre, email, tipo, telefono);
            JOptionPane.showMessageDialog(null, "Exito al registrar Usuario");

            if (consultasMongoDB.insertarUsuario(nombre, email, tipo, telefono)) {
                JOptionPane.showMessageDialog(null, "Exito al registrar Usuario con mongodb");
            } else {
                JOptionPane.showMessageDialog(null, "ERROR al registrar Usuario con mongodb");
            }
            if (consultasDB4O.insertarUsuario(usuario)) {
                JOptionPane.showMessageDialog(null, "Exito al registrar Usuario con DB4O");
            } else {
                JOptionPane.showMessageDialog(null, "ERROR al registrar Usuario con DB4O");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Error al registrar, revise los campos\nNumero de SOLO 7 Digitos.\nCorreo abcde@fghi.com.\nNombre no puede tener digitos.\nNo puede ser ni nulo ni vacio");
        }


    }//GEN-LAST:event_btnAceptarMouseClicked

    private void cbTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoUsuarioActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cbTipoUsuario;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTfno;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
